<a href="https://colab.research.google.com/github/AnastasiaLytvyn/BigData/blob/main/Labs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Робота буде виконана в серодовищі Google Colab.
Встановимо PySpark

In [ ]:
pip install pyspark

Collecting pyspark
  Downloading pyspark-3.5.3.tar.gz (317.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.3/317.3 MB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.3-py2.py3-none-any.whl size=317840625 sha256=f24083d87c839f503177bd4782afb604d490276538a3b16705c6bee1e407842b
  Stored in directory: /root/.cache/pip/wheels/1b/3a/92/28b93e2fbfdbb07509ca4d6f50c5e407f48dce4ddbda69a4ab
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.3

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import *

In [ ]:
spark = SparkSession.builder.appName("Anastasiia Lytvyn IS-42mp LAB-1").getOrCreate()

Створимо схему для датафрейму Студенти. Створимо дані для датафреймів.
Також створимо самі датафрейми

In [ ]:
Myschema = StructType([
    StructField("Ім'я студента", StringType(), False),
    StructField("Прізвище студента", StringType(), False),
    StructField("Група студента", StringType(), False),
    StructField("Кафедра студента", StringType(), False)
])

data_it = [
    ("Анастасія", "Петренко", "ІТ-21", "Кафедра інформаційних технологій"),
    ("Олексій", "Іванов", "ІТ-21", "Кафедра інформаційних технологій"),
    ("Марія", "Шевченко", "ІТ-22", "Кафедра інформаційних технологій"),
    ("Ігор", "Коваленко", "ІТ-23", "Кафедра інформаційних технологій")
]

data_economics = [
    ("Олена", "Ткаченко", "ФЕ-21", "Кафедра економіки"),
    ("Дмитро", "Климов", "ФЕ-22", "Кафедра економіки"),
    ("Вікторія", "Мельник", "ФЕ-23", "Кафедра економіки"),
    ("Сергій", "Поліщук", "ФЕ-24", "Кафедра економіки")
]

In [ ]:
df_it = spark.createDataFrame(data_it, Myschema)
df_economics = spark.createDataFrame(data_economics, Myschema)
df_it.printSchema()
df_economics.printSchema()

root
 |-- Ім'я студента: string (nullable = false)
 |-- Прізвище студента: string (nullable = false)
 |-- Група студента: string (nullable = false)
 |-- Кафедра студента: string (nullable = false)

root
 |-- Ім'я студента: string (nullable = false)
 |-- Прізвище студента: string (nullable = false)
 |-- Група студента: string (nullable = false)
 |-- Кафедра студента: string (nullable = false)

Об'єднаємо два датафрейми в один

In [ ]:
df_university = df_it.union(df_economics)
df_university.show()

+-------------+-----------------+--------------+--------------------+
|Ім'я студента|Прізвище студента|Група студента|    Кафедра студента|
+-------------+-----------------+--------------+--------------------+
|    Анастасія|         Петренко|         ІТ-21|Кафедра інформаці...|
|      Олексій|           Іванов|         ІТ-21|Кафедра інформаці...|
|        Марія|         Шевченко|         ІТ-22|Кафедра інформаці...|
|         Ігор|        Коваленко|         ІТ-23|Кафедра інформаці...|
|        Олена|         Ткаченко|         ФЕ-21|   Кафедра економіки|
|       Дмитро|           Климов|         ФЕ-22|   Кафедра економіки|
|     Вікторія|          Мельник|         ФЕ-23|   Кафедра економіки|
|       Сергій|          Поліщук|         ФЕ-24|   Кафедра економіки|
+-------------+-----------------+--------------+--------------------+

Додамо нову колонку

In [ ]:
df_university=df_university.withColumn("Бюджетна форма навчання", when(rand() < 0.5, True).otherwise(False))
df_university.show()

+-------------+-----------------+--------------+--------------------+-----------------------+
|Ім'я студента|Прізвище студента|Група студента|    Кафедра студента|Бюджетна форма навчання|
+-------------+-----------------+--------------+--------------------+-----------------------+
|    Анастасія|         Петренко|         ІТ-21|Кафедра інформаці...|                  false|
|      Олексій|           Іванов|         ІТ-21|Кафедра інформаці...|                  false|
|        Марія|         Шевченко|         ІТ-22|Кафедра інформаці...|                  false|
|         Ігор|        Коваленко|         ІТ-23|Кафедра інформаці...|                  false|
|        Олена|         Ткаченко|         ФЕ-21|   Кафедра економіки|                  false|
|       Дмитро|           Климов|         ФЕ-22|   Кафедра економіки|                  false|
|     Вікторія|          Мельник|         ФЕ-23|   Кафедра економіки|                   true|
|       Сергій|          Поліщук|         ФЕ-24|   Кафедра економіки|                   true|
+-------------+-----------------+--------------+--------------------+-----------------------+

Додамо новий рядок

In [ ]:
df_university=df_university.union(spark.createDataFrame([("Іван", "Григоренко", "ІТ-24", "Кафедра інформаційних технологій", False)], df_university.schema))
df_university.show()

+-------------+-----------------+--------------+--------------------+-----------------------+
|Ім'я студента|Прізвище студента|Група студента|    Кафедра студента|Бюджетна форма навчання|
+-------------+-----------------+--------------+--------------------+-----------------------+
|    Анастасія|         Петренко|         ІТ-21|Кафедра інформаці...|                  false|
|      Олексій|           Іванов|         ІТ-21|Кафедра інформаці...|                  false|
|        Марія|         Шевченко|         ІТ-22|Кафедра інформаці...|                  false|
|         Ігор|        Коваленко|         ІТ-23|Кафедра інформаці...|                  false|
|        Олена|         Ткаченко|         ФЕ-21|   Кафедра економіки|                  false|
|       Дмитро|           Климов|         ФЕ-22|   Кафедра економіки|                  false|
|     Вікторія|          Мельник|         ФЕ-23|   Кафедра економіки|                   true|
|       Сергій|          Поліщук|         ФЕ-24|   Кафедра економіки|                   true|
|         Іван|       Григоренко|         ІТ-24|Кафедра інформаці...|                  false|
+-------------+-----------------+--------------+--------------------+-----------------------+

Видалимо рядок

In [ ]:
df_university = df_university.filter(df_university["Група студента"]!="ІТ-24")
df_university.show()

+-------------+-----------------+--------------+--------------------+-----------------------+
|Ім'я студента|Прізвище студента|Група студента|    Кафедра студента|Бюджетна форма навчання|
+-------------+-----------------+--------------+--------------------+-----------------------+
|    Анастасія|         Петренко|         ІТ-21|Кафедра інформаці...|                  false|
|      Олексій|           Іванов|         ІТ-21|Кафедра інформаці...|                  false|
|        Марія|         Шевченко|         ІТ-22|Кафедра інформаці...|                  false|
|         Ігор|        Коваленко|         ІТ-23|Кафедра інформаці...|                  false|
|        Олена|         Ткаченко|         ФЕ-21|   Кафедра економіки|                  false|
|       Дмитро|           Климов|         ФЕ-22|   Кафедра економіки|                  false|
|     Вікторія|          Мельник|         ФЕ-23|   Кафедра економіки|                   true|
|       Сергій|          Поліщук|         ФЕ-24|   Кафедра економіки|                   true|
+-------------+-----------------+--------------+--------------------+-----------------------+

Видалимо стовпець

In [ ]:
df_university = df_university.drop("Кафедра студента")
df_university.show()

+-------------+-----------------+--------------+-----------------------+
|Ім'я студента|Прізвище студента|Група студента|Бюджетна форма навчання|
+-------------+-----------------+--------------+-----------------------+
|    Анастасія|         Петренко|         ІТ-21|                  false|
|      Олексій|           Іванов|         ІТ-21|                  false|
|        Марія|         Шевченко|         ІТ-22|                  false|
|         Ігор|        Коваленко|         ІТ-23|                  false|
|        Олена|         Ткаченко|         ФЕ-21|                  false|
|       Дмитро|           Климов|         ФЕ-22|                  false|
|     Вікторія|          Мельник|         ФЕ-23|                   true|
|       Сергій|          Поліщук|         ФЕ-24|                   true|
+-------------+-----------------+--------------+-----------------------+

In [ ]:
spark.stop()

Варіант 3

In [ ]:
spark = SparkSession.builder.appName("Anastasiia Lytvyn IS-42mp LAB-1 Possum").getOrCreate()

Створити свою схему та завантажити дані з файлу, виконати дії
відповідно до варіанту.

In [ ]:
Myschema = StructType([
    StructField("", IntegerType(), True),
    StructField("case", IntegerType(), True),
    StructField("site", IntegerType(), True),
    StructField("Pop", StringType(), True),
    StructField("sex", StringType(), True),
    StructField("age", DoubleType(), True),
    StructField("hdlngth", DoubleType(), True),
    StructField("skullw", DoubleType(), True),
    StructField("totlngth", DoubleType(), True),
    StructField("taill", DoubleType(), True),
    StructField("footlgth", DoubleType(), True),
    StructField("earconch", DoubleType(), True),
    StructField("eye", DoubleType(), True),
    StructField("chest", DoubleType(), True),
    StructField("belly", DoubleType(), True)
])

In [ ]:
df=spark.read.csv("/content/possum.csv", header=True, schema=Myschema)
df = df.drop("")
df.printSchema()

root
 |-- case: integer (nullable = true)
 |-- site: integer (nullable = true)
 |-- Pop: string (nullable = true)
 |-- sex: string (nullable = true)
 |-- age: double (nullable = true)
 |-- hdlngth: double (nullable = true)
 |-- skullw: double (nullable = true)
 |-- totlngth: double (nullable = true)
 |-- taill: double (nullable = true)
 |-- footlgth: double (nullable = true)
 |-- earconch: double (nullable = true)
 |-- eye: double (nullable = true)
 |-- chest: double (nullable = true)
 |-- belly: double (nullable = true)

In [ ]:
df.show(105)

+----+----+-----+---+---+-------+------+--------+-----+--------+--------+----+-----+-----+
|case|site|  Pop|sex|age|hdlngth|skullw|totlngth|taill|footlgth|earconch| eye|chest|belly|
+----+----+-----+---+---+-------+------+--------+-----+--------+--------+----+-----+-----+
|   1|   1|  Vic|  m|8.0|   94.1|  60.4|    89.0| 36.0|    74.5|    54.5|15.2| 28.0| 36.0|
|   2|   1|  Vic|  f|6.0|   92.5|  57.6|    91.5| 36.5|    72.5|    51.2|16.0| 28.5| 33.0|
|   3|   1|  Vic|  f|6.0|   94.0|  60.0|    95.5| 39.0|    75.4|    51.9|15.5| 30.0| 34.0|
|   4|   1|  Vic|  f|6.0|   93.2|  57.1|    92.0| 38.0|    76.1|    52.2|15.2| 28.0| 34.0|
|   5|   1|  Vic|  f|2.0|   91.5|  56.3|    85.5| 36.0|    71.0|    53.2|15.1| 28.5| 33.0|
|   6|   1|  Vic|  f|1.0|   93.1|  54.8|    90.5| 35.5|    73.2|    53.6|14.2| 30.0| 32.0|
|   7|   1|  Vic|  m|2.0|   95.3|  58.2|    89.5| 36.0|    71.5|    52.0|14.2| 30.0| 34.5|
|   8|   1|  Vic|  f|6.0|   94.8|  57.6|    91.0| 37.0|    72.7|    53.9|14.5| 29.0| 34.0|
|   9|   1|  Vic|  f|9.0|   93.4|  56.3|    91.5| 37.0|    72.4|    52.9|15.5| 28.0| 33.0|
|  10|   1|  Vic|  f|6.0|   91.8|  58.0|    89.5| 37.5|    70.9|    53.4|14.4| 27.5| 32.0|
|  11|   1|  Vic|  f|9.0|   93.3|  57.2|    89.5| 39.0|    77.2|    51.3|14.9| 31.0| 34.0|
|  12|   1|  Vic|  f|5.0|   94.9|  55.6|    92.0| 35.5|    71.7|    51.0|15.3| 28.0| 33.0|
|  13|   1|  Vic|  m|5.0|   95.1|  59.9|    89.5| 36.0|    71.0|    49.8|15.8| 27.0| 32.0|
|  14|   1|  Vic|  m|3.0|   95.4|  57.6|    91.5| 36.0|    74.3|    53.7|15.1| 28.0| 31.5|
|  15|   1|  Vic|  m|5.0|   92.9|  57.6|    85.5| 34.0|    69.7|    51.8|15.7| 28.0| 35.0|
|  16|   1|  Vic|  m|4.0|   91.6|  56.0|    86.0| 34.5|    73.0|    51.4|14.4| 28.0| 32.0|
|  17|   1|  Vic|  f|1.0|   94.7|  67.7|    89.5| 36.5|    73.2|    53.2|14.7| 29.0| 31.0|
|  18|   1|  Vic|  m|2.0|   93.5|  55.7|    90.0| 36.0|    73.7|    55.4|15.3| 28.0| 32.0|
|  19|   1|  Vic|  f|5.0|   94.4|  55.4|    90.5| 35.0|    73.4|    53.9|15.2| 28.0| 32.0|
|  20|   1|  Vic|  f|4.0|   94.8|  56.3|    89.0| 38.0|    73.8|    52.4|15.5| 27.0| 36.0|
|  21|   1|  Vic|  f|3.0|   95.9|  58.1|    96.5| 39.5|    77.9|    52.9|14.2| 30.0| 40.0|
|  22|   1|  Vic|  m|3.0|   96.3|  58.5|    91.0| 39.5|    73.5|    52.1|16.2| 28.0| 36.0|
|  23|   1|  Vic|  f|4.0|   92.5|  56.1|    89.0| 36.0|    72.8|    53.3|15.4| 28.0| 35.0|
|  24|   1|  Vic|  m|2.0|   94.4|  54.9|    84.0| 34.0|    75.0|    53.5|16.2| 27.0| 32.0|
|  25|   1|  Vic|  m|3.0|   95.8|  58.5|    91.5| 35.5|    72.3|    51.6|14.9| 31.0| 35.0|
|  26|   1|  Vic|  m|7.0|   96.0|  59.0|    90.0| 36.0|    73.6|    56.2|15.0| 29.0| 38.0|
|  27|   1|  Vic|  f|2.0|   90.5|  54.5|    85.0| 35.0|    70.3|    50.8|14.2| 23.0| 28.0|
|  28|   1|  Vic|  m|4.0|   93.8|  56.8|    87.0| 34.5|    73.2|    53.0|15.3| 27.0| 30.0|
|  29|   1|  Vic|  f|3.0|   92.8|  56.0|    88.0| 35.0|    74.9|    51.8|14.0| 24.0| 32.0|
|  30|   1|  Vic|  f|2.0|   92.1|  54.4|    84.0| 33.5|    70.6|    50.8|14.5| 24.5| 33.0|
|  31|   1|  Vic|  m|3.0|   92.8|  54.1|    93.0| 37.0|    68.0|    52.5|14.5| 27.0| 31.0|
|  32|   1|  Vic|  f|4.0|   94.3|  56.7|    94.0| 39.0|    74.8|    52.0|14.9| 28.0| 34.0|
|  33|   1|  Vic|  m|3.0|   91.4|  54.6|    89.0| 37.0|    70.8|    51.8|14.8| 24.0| 30.0|
|  34|   2|  Vic|  m|2.0|   90.6|  55.7|    85.5| 36.5|    73.1|    53.1|14.4| 26.0| 28.5|
|  35|   2|  Vic|  m|4.0|   94.4|  57.9|    85.0| 35.5|    71.2|    55.5|16.4| 28.0| 35.5|
|  36|   2|  Vic|  m|7.0|   93.3|  59.3|    88.0| 35.0|    74.3|    52.0|14.9| 25.5| 36.0|
|  37|   2|  Vic|  f|2.0|   89.3|  54.8|    82.5| 35.0|    71.2|    52.0|13.6| 28.0| 31.5|
|  38|   2|  Vic|  m|7.0|   92.4|  56.0|    80.5| 35.5|    68.4|    49.5|15.9| 27.0| 30.0|
|  39|   2|  Vic|  f|1.0|   84.7|  51.5|    75.0| 34.0|    68.7|    53.4|13.0| 25.0| 25.0|
|  40|   2|  Vic|  f|3.0|   91.0|  55.0|    84.5| 36.0|    72.8|    51.4|13.6| 27.0| 30.0|
|  42|   2|  Vic|  m|3.0|   85.3|  54.1|    77.0| 32.0|    62.7|    51.2|13.8| 25.5| 33.0|
|  43|   2|  Vic|  f|2.0|   90.0|  55.5|    81.0| 32.0|    72.0|    49.4|13.4| 29.0| 31.0|
|  45|   2|  Vic|  m|3.0|   90.7|  55.9|    81.0| 34.0|    71.5|    54.0|14.6| 27.0| 31.5|
|  47|   3|other|  m|2.0|   90.1|  54.8|    89.0| 37.5|    66.0|    45.5|15.0| 25.0| 33.0|
|  48|   3|other|  m|5.0|   98.6|  63.2|    85.0| 34.0|    66.9|    44.9|17.0| 28.0| 35.0|
|  49|   3|other|  m|4.0|   95.4|  59.2|    85.0| 37.0|    69.0|    45.0|15.9| 29.5| 35.5|
|  50|   3|other|  f|5.0|   91.6|  56.4|    88.0| 38.0|    65.0|    47.2|14.9| 28.0| 36.0|
|  51|   3|other|  f|5.0|   95.6|  59.6|    85.0| 36.0|    64.0|    43.9|17.4| 28.0| 38.5|
|  52|   3|other|  m|6.0|   97.6|  61.0|    93.5| 40.0|    67.9|    44.3|15.8| 28.5| 32.5|
|  53|   3|other|  f|3.0|   93.1|  58.1|    91.0| 38.0|    67.4|    46.0|16.5| 26.0| 33.5|
|  54|   4|other|  m|7.0|   96.9|  63.0|    91.5| 43.0|    71.3|    46.0|17.5| 30.0| 36.5|
|  55|   4|other|  m|2.0|  103.1|  63.2|    92.5| 38.0|    72.5|    44.9|16.4| 30.5| 36.0|
|  56|   4|other|  m|3.0|   99.9|  61.5|    93.7| 38.0|    68.7|    46.8|16.4| 27.5| 31.5|
|  57|   4|other|  f|4.0|   95.1|  59.4|    93.0| 41.0|    67.2|    45.3|14.5| 31.0| 39.0|
|  58|   4|other|  m|3.0|   94.5|  64.2|    91.0| 39.0|    66.5|    46.4|14.4| 30.5| 33.0|
|  59|   4|other|  m|2.0|  102.5|  62.8|    96.0| 40.0|    73.2|    44.5|14.7| 32.0| 36.0|
|  60|   4|other|  f|2.0|   91.3|  57.7|    88.0| 39.0|    63.1|    47.0|14.4| 26.0| 30.0|
|  61|   5|other|  m|7.0|   95.7|  59.0|    86.0| 38.0|    63.1|    44.9|15.0| 26.5| 31.0|
|  62|   5|other|  f|3.0|   91.3|  58.0|    90.5| 39.0|    65.5|    41.3|16.0| 27.0| 32.0|
|  63|   5|other|  f|6.0|   92.0|  56.4|    88.5| 38.0|    64.1|    46.3|15.2| 25.5| 28.5|
|  64|   5|other|  f|3.0|   96.9|  56.5|    89.5| 38.5|    63.0|    45.1|17.1| 25.5| 33.0|
|  65|   5|other|  f|5.0|   93.5|  57.4|    88.5| 38.0|    68.2|    41.7|14.0| 29.0| 38.5|
|  66|   5|other|  f|3.0|   90.4|  55.8|    86.0| 36.5|    63.2|    44.2|15.7| 26.5| 34.0|
|  67|   5|other|  m|4.0|   93.3|  57.6|    85.0| 36.5|    64.7|    44.1|16.5| 27.5| 29.5|
|  68|   5|other|  m|5.0|   94.1|  56.0|    88.5| 38.0|    65.9|    43.1|17.4| 27.0| 30.0|
|  69|   5|other|  m|5.0|   98.0|  55.6|    88.0| 37.5|    65.0|    45.6|15.0| 28.5| 34.0|
|  70|   5|other|  f|7.0|   91.9|  56.4|    87.0| 38.0|    65.4|    44.1|13.0| 27.0| 34.0|
|  71|   5|other|  m|6.0|   92.8|  57.6|    90.0| 40.0|    65.7|    42.8|15.0| 27.5| 34.0|
|  72|   5|other|  m|1.0|   85.9|  52.4|    80.5| 35.0|    62.0|    42.4|14.1| 25.5| 30.0|
|  73|   5|other|  m|1.0|   82.5|  52.3|    82.0| 36.5|    65.7|    44.7|16.0| 23.5| 28.0|
|  74|   6|other|  f|4.0|   88.7|  52.0|    83.0| 38.0|    61.5|    45.9|14.7| 26.0| 34.0|
|  75|   6|other|  m|6.0|   93.8|  58.1|    89.0| 38.0|    66.2|    45.6|16.9| 26.0| 33.5|
|  76|   6|other|  m|5.0|   92.4|  56.8|    89.0| 41.0|    64.5|    46.4|17.8| 26.0| 33.0|
|  77|   6|other|  m|6.0|   93.6|  56.2|    84.0| 36.0|    62.8|    42.9|16.2| 25.0| 35.0|
|  78|   6|other|  m|1.0|   86.5|  51.0|    81.0| 36.5|    63.0|    44.3|13.2| 23.0| 28.0|
|  79|   6|other|  m|1.0|   85.8|  50.0|    81.0| 36.5|    62.8|    43.0|14.8| 22.0| 28.5|
|  80|   6|other|  m|1.0|   86.7|  52.6|    84.0| 38.0|    62.3|    44.8|15.0| 23.5| 30.5|
|  81|   6|other|  m|3.0|   90.6|  56.0|    85.5| 38.0|    65.6|    41.7|17.0| 27.5| 35.0|
|  82|   6|other|  f|4.0|   86.0|  54.0|    82.0| 36.5|    60.7|    42.9|15.4| 26.0| 32.0|
|  83|   6|other|  f|3.0|   90.0|  53.8|    81.5| 36.0|    62.0|    43.3|14.0| 25.0| 29.0|
|  84|   6|other|  m|3.0|   88.4|  54.6|    80.5| 36.0|    62.6|    43.6|16.3| 25.0| 28.5|
|  85|   6|other|  m|3.0|   89.5|  56.2|    92.0| 40.5|    65.6|    43.5|14.5| 27.0| 31.5|
|  86|   6|other|  f|3.0|   88.2|  53.2|    86.5| 38.5|    60.3|    43.7|13.6| 26.0| 31.0|
|  87|   7|other|  m|2.0|   98.5|  60.7|    93.0| 41.5|    71.7|    46.8|15.0| 26.0| 36.0|
|  88|   7|other|  f|2.0|   89.6|  58.0|    87.5| 38.0|    66.7|    43.5|16.0| 25.5| 31.5|
|  89|   7|other|  m|6.0|   97.7|  58.4|    84.5| 35.0|    64.4|    46.2|14.4| 29.0| 30.5|
|  90|   7|other|  m|3.0|   92.6|  54.6|    85.0| 38.5|    69.8|    44.8|14.5| 25.5| 32.5|
|  91|   7|other|  m|3.0|   97.8|  59.6|    89.0| 38.0|    65.5|    48.0|15.0| 26.0| 32.0|
|  92|   7|other|  m|2.0|   90.7|  56.3|    85.0| 37.0|    67.6|    46.8|14.5| 25.5| 31.0|
|  93|   7|other|  m|3.0|   89.2|  54.0|    82.0| 38.0|    63.8|    44.9|12.8| 24.0| 31.0|
|  94|   7|other|  m|7.0|   91.8|  57.6|    84.0| 35.5|    64.2|    45.1|14.4| 29.0| 35.0|
|  95|   7|other|  m|4.0|   91.6|  56.6|    88.5| 37.5|    64.5|    45.4|14.9| 27.0| 31.0|
|  96|   7|other|  m|4.0|   94.8|  55.7|    83.0| 38.0|    66.5|    47.7|14.0| 25.0| 33.0|
|  97|   7|other|  m|3.0|   91.0|  53.1|    86.0| 38.0|    63.8|    46.0|14.5| 25.0| 31.5|
|  98|   7|other|  m|5.0|   93.2|  68.6|    84.0| 35.0|    65.6|    44.3|14.5| 28.5| 32.0|
|  99|   7|other|  f|3.0|   93.3|  56.2|    86.5| 38.5|    64.8|    43.8|14.0| 28.0| 35.0|
| 100|   7|other|  m|1.0|   89.5|  56.0|    81.5| 36.5|    66.0|    46.8|14.8| 23.0| 27.0|
| 101|   7|other|  m|1.0|   88.6|  54.7|    82.5| 39.0|    64.4|    48.0|14.0| 25.0| 33.0|
| 102|   7|other|  f|6.0|   92.4|  55.0|    89.0| 38.0|    63.5|    45.4|13.0| 25.0| 30.0|
| 103|   7|other|  m|4.0|   91.5|  55.2|    82.5| 36.5|    62.9|    45.9|15.4| 25.0| 29.0|
| 104|   7|other|  f|3.0|   93.6|  59.9|    89.0| 40.0|    67.6|    46.0|14.8| 28.5| 33.5|
+----+----+-----+---+---+-------+------+--------+-----+--------+--------+----+-----+-----+

1. Вивести вік всіх самиць з провінції Вікторія.

In [ ]:
df.select("age").filter( (col("Pop") == "Vic") & (col("sex") == "f") ).show(105)

+---+
|age|
+---+
|6.0|
|6.0|
|6.0|
|2.0|
|1.0|
|6.0|
|9.0|
|6.0|
|9.0|
|5.0|
|1.0|
|5.0|
|4.0|
|3.0|
|4.0|
|2.0|
|3.0|
|2.0|
|4.0|
|2.0|
|1.0|
|3.0|
|2.0|
+---+

2. Порахувати загальну популяцію опосумів усіх провінцій, крім
Вікторії.

In [ ]:
df.filter(col("Pop") != "Vic").count()

58

3. Порахувати середню довжину хвоста самців.

In [ ]:
df.filter(col("sex") == "m").agg({"taill": "avg"}).show()

+----------+
|avg(taill)|
+----------+
|      37.0|
+----------+

4. Відсортувати дані за загальною довжиною тіла (спадаючий
порядок); за віком (зростаючий).

In [ ]:
df.orderBy(col("totlngth").desc(), col("age").asc()).show(50)

+----+----+-----+---+---+-------+------+--------+-----+--------+--------+----+-----+-----+
|case|site|  Pop|sex|age|hdlngth|skullw|totlngth|taill|footlgth|earconch| eye|chest|belly|
+----+----+-----+---+---+-------+------+--------+-----+--------+--------+----+-----+-----+
|  21|   1|  Vic|  f|3.0|   95.9|  58.1|    96.5| 39.5|    77.9|    52.9|14.2| 30.0| 40.0|
|  59|   4|other|  m|2.0|  102.5|  62.8|    96.0| 40.0|    73.2|    44.5|14.7| 32.0| 36.0|
|   3|   1|  Vic|  f|6.0|   94.0|  60.0|    95.5| 39.0|    75.4|    51.9|15.5| 30.0| 34.0|
|  32|   1|  Vic|  f|4.0|   94.3|  56.7|    94.0| 39.0|    74.8|    52.0|14.9| 28.0| 34.0|
|  56|   4|other|  m|3.0|   99.9|  61.5|    93.7| 38.0|    68.7|    46.8|16.4| 27.5| 31.5|
|  52|   3|other|  m|6.0|   97.6|  61.0|    93.5| 40.0|    67.9|    44.3|15.8| 28.5| 32.5|
|  87|   7|other|  m|2.0|   98.5|  60.7|    93.0| 41.5|    71.7|    46.8|15.0| 26.0| 36.0|
|  31|   1|  Vic|  m|3.0|   92.8|  54.1|    93.0| 37.0|    68.0|    52.5|14.5| 27.0| 31.0|
|  57|   4|other|  f|4.0|   95.1|  59.4|    93.0| 41.0|    67.2|    45.3|14.5| 31.0| 39.0|
|  55|   4|other|  m|2.0|  103.1|  63.2|    92.5| 38.0|    72.5|    44.9|16.4| 30.5| 36.0|
|  85|   6|other|  m|3.0|   89.5|  56.2|    92.0| 40.5|    65.6|    43.5|14.5| 27.0| 31.5|
|  12|   1|  Vic|  f|5.0|   94.9|  55.6|    92.0| 35.5|    71.7|    51.0|15.3| 28.0| 33.0|
|   4|   1|  Vic|  f|6.0|   93.2|  57.1|    92.0| 38.0|    76.1|    52.2|15.2| 28.0| 34.0|
|  14|   1|  Vic|  m|3.0|   95.4|  57.6|    91.5| 36.0|    74.3|    53.7|15.1| 28.0| 31.5|
|  25|   1|  Vic|  m|3.0|   95.8|  58.5|    91.5| 35.5|    72.3|    51.6|14.9| 31.0| 35.0|
|   2|   1|  Vic|  f|6.0|   92.5|  57.6|    91.5| 36.5|    72.5|    51.2|16.0| 28.5| 33.0|
|  54|   4|other|  m|7.0|   96.9|  63.0|    91.5| 43.0|    71.3|    46.0|17.5| 30.0| 36.5|
|   9|   1|  Vic|  f|9.0|   93.4|  56.3|    91.5| 37.0|    72.4|    52.9|15.5| 28.0| 33.0|
|  22|   1|  Vic|  m|3.0|   96.3|  58.5|    91.0| 39.5|    73.5|    52.1|16.2| 28.0| 36.0|
|  53|   3|other|  f|3.0|   93.1|  58.1|    91.0| 38.0|    67.4|    46.0|16.5| 26.0| 33.5|
|  58|   4|other|  m|3.0|   94.5|  64.2|    91.0| 39.0|    66.5|    46.4|14.4| 30.5| 33.0|
|   8|   1|  Vic|  f|6.0|   94.8|  57.6|    91.0| 37.0|    72.7|    53.9|14.5| 29.0| 34.0|
|   6|   1|  Vic|  f|1.0|   93.1|  54.8|    90.5| 35.5|    73.2|    53.6|14.2| 30.0| 32.0|
|  62|   5|other|  f|3.0|   91.3|  58.0|    90.5| 39.0|    65.5|    41.3|16.0| 27.0| 32.0|
|  19|   1|  Vic|  f|5.0|   94.4|  55.4|    90.5| 35.0|    73.4|    53.9|15.2| 28.0| 32.0|
|  18|   1|  Vic|  m|2.0|   93.5|  55.7|    90.0| 36.0|    73.7|    55.4|15.3| 28.0| 32.0|
|  71|   5|other|  m|6.0|   92.8|  57.6|    90.0| 40.0|    65.7|    42.8|15.0| 27.5| 34.0|
|  26|   1|  Vic|  m|7.0|   96.0|  59.0|    90.0| 36.0|    73.6|    56.2|15.0| 29.0| 38.0|
|  17|   1|  Vic|  f|1.0|   94.7|  67.7|    89.5| 36.5|    73.2|    53.2|14.7| 29.0| 31.0|
|   7|   1|  Vic|  m|2.0|   95.3|  58.2|    89.5| 36.0|    71.5|    52.0|14.2| 30.0| 34.5|
|  64|   5|other|  f|3.0|   96.9|  56.5|    89.5| 38.5|    63.0|    45.1|17.1| 25.5| 33.0|
|  13|   1|  Vic|  m|5.0|   95.1|  59.9|    89.5| 36.0|    71.0|    49.8|15.8| 27.0| 32.0|
|  10|   1|  Vic|  f|6.0|   91.8|  58.0|    89.5| 37.5|    70.9|    53.4|14.4| 27.5| 32.0|
|  11|   1|  Vic|  f|9.0|   93.3|  57.2|    89.5| 39.0|    77.2|    51.3|14.9| 31.0| 34.0|
|  47|   3|other|  m|2.0|   90.1|  54.8|    89.0| 37.5|    66.0|    45.5|15.0| 25.0| 33.0|
|  33|   1|  Vic|  m|3.0|   91.4|  54.6|    89.0| 37.0|    70.8|    51.8|14.8| 24.0| 30.0|
|  91|   7|other|  m|3.0|   97.8|  59.6|    89.0| 38.0|    65.5|    48.0|15.0| 26.0| 32.0|
| 104|   7|other|  f|3.0|   93.6|  59.9|    89.0| 40.0|    67.6|    46.0|14.8| 28.5| 33.5|
|  20|   1|  Vic|  f|4.0|   94.8|  56.3|    89.0| 38.0|    73.8|    52.4|15.5| 27.0| 36.0|
|  23|   1|  Vic|  f|4.0|   92.5|  56.1|    89.0| 36.0|    72.8|    53.3|15.4| 28.0| 35.0|
|  76|   6|other|  m|5.0|   92.4|  56.8|    89.0| 41.0|    64.5|    46.4|17.8| 26.0| 33.0|
|  75|   6|other|  m|6.0|   93.8|  58.1|    89.0| 38.0|    66.2|    45.6|16.9| 26.0| 33.5|
| 102|   7|other|  f|6.0|   92.4|  55.0|    89.0| 38.0|    63.5|    45.4|13.0| 25.0| 30.0|
|   1|   1|  Vic|  m|8.0|   94.1|  60.4|    89.0| 36.0|    74.5|    54.5|15.2| 28.0| 36.0|
|  95|   7|other|  m|4.0|   91.6|  56.6|    88.5| 37.5|    64.5|    45.4|14.9| 27.0| 31.0|
|  65|   5|other|  f|5.0|   93.5|  57.4|    88.5| 38.0|    68.2|    41.7|14.0| 29.0| 38.5|
|  68|   5|other|  m|5.0|   94.1|  56.0|    88.5| 38.0|    65.9|    43.1|17.4| 27.0| 30.0|
|  63|   5|other|  f|6.0|   92.0|  56.4|    88.5| 38.0|    64.1|    46.3|15.2| 25.5| 28.5|
|  60|   4|other|  f|2.0|   91.3|  57.7|    88.0| 39.0|    63.1|    47.0|14.4| 26.0| 30.0|
|  29|   1|  Vic|  f|3.0|   92.8|  56.0|    88.0| 35.0|    74.9|    51.8|14.0| 24.0| 32.0|
+----+----+-----+---+---+-------+------+--------+-----+--------+--------+----+-----+-----+
only showing top 50 rows

In [ ]:
df.orderBy(col("age").asc(),col("totlngth").desc()).show(50)

+----+----+-----+---+---+-------+------+--------+-----+--------+--------+----+-----+-----+
|case|site|  Pop|sex|age|hdlngth|skullw|totlngth|taill|footlgth|earconch| eye|chest|belly|
+----+----+-----+---+---+-------+------+--------+-----+--------+--------+----+-----+-----+
|   6|   1|  Vic|  f|1.0|   93.1|  54.8|    90.5| 35.5|    73.2|    53.6|14.2| 30.0| 32.0|
|  17|   1|  Vic|  f|1.0|   94.7|  67.7|    89.5| 36.5|    73.2|    53.2|14.7| 29.0| 31.0|
|  80|   6|other|  m|1.0|   86.7|  52.6|    84.0| 38.0|    62.3|    44.8|15.0| 23.5| 30.5|
| 101|   7|other|  m|1.0|   88.6|  54.7|    82.5| 39.0|    64.4|    48.0|14.0| 25.0| 33.0|
|  73|   5|other|  m|1.0|   82.5|  52.3|    82.0| 36.5|    65.7|    44.7|16.0| 23.5| 28.0|
| 100|   7|other|  m|1.0|   89.5|  56.0|    81.5| 36.5|    66.0|    46.8|14.8| 23.0| 27.0|
|  78|   6|other|  m|1.0|   86.5|  51.0|    81.0| 36.5|    63.0|    44.3|13.2| 23.0| 28.0|
|  79|   6|other|  m|1.0|   85.8|  50.0|    81.0| 36.5|    62.8|    43.0|14.8| 22.0| 28.5|
|  72|   5|other|  m|1.0|   85.9|  52.4|    80.5| 35.0|    62.0|    42.4|14.1| 25.5| 30.0|
|  39|   2|  Vic|  f|1.0|   84.7|  51.5|    75.0| 34.0|    68.7|    53.4|13.0| 25.0| 25.0|
|  59|   4|other|  m|2.0|  102.5|  62.8|    96.0| 40.0|    73.2|    44.5|14.7| 32.0| 36.0|
|  87|   7|other|  m|2.0|   98.5|  60.7|    93.0| 41.5|    71.7|    46.8|15.0| 26.0| 36.0|
|  55|   4|other|  m|2.0|  103.1|  63.2|    92.5| 38.0|    72.5|    44.9|16.4| 30.5| 36.0|
|  18|   1|  Vic|  m|2.0|   93.5|  55.7|    90.0| 36.0|    73.7|    55.4|15.3| 28.0| 32.0|
|   7|   1|  Vic|  m|2.0|   95.3|  58.2|    89.5| 36.0|    71.5|    52.0|14.2| 30.0| 34.5|
|  47|   3|other|  m|2.0|   90.1|  54.8|    89.0| 37.5|    66.0|    45.5|15.0| 25.0| 33.0|
|  60|   4|other|  f|2.0|   91.3|  57.7|    88.0| 39.0|    63.1|    47.0|14.4| 26.0| 30.0|
|  88|   7|other|  f|2.0|   89.6|  58.0|    87.5| 38.0|    66.7|    43.5|16.0| 25.5| 31.5|
|   5|   1|  Vic|  f|2.0|   91.5|  56.3|    85.5| 36.0|    71.0|    53.2|15.1| 28.5| 33.0|
|  34|   2|  Vic|  m|2.0|   90.6|  55.7|    85.5| 36.5|    73.1|    53.1|14.4| 26.0| 28.5|
|  27|   1|  Vic|  f|2.0|   90.5|  54.5|    85.0| 35.0|    70.3|    50.8|14.2| 23.0| 28.0|
|  92|   7|other|  m|2.0|   90.7|  56.3|    85.0| 37.0|    67.6|    46.8|14.5| 25.5| 31.0|
|  24|   1|  Vic|  m|2.0|   94.4|  54.9|    84.0| 34.0|    75.0|    53.5|16.2| 27.0| 32.0|
|  30|   1|  Vic|  f|2.0|   92.1|  54.4|    84.0| 33.5|    70.6|    50.8|14.5| 24.5| 33.0|
|  37|   2|  Vic|  f|2.0|   89.3|  54.8|    82.5| 35.0|    71.2|    52.0|13.6| 28.0| 31.5|
|  43|   2|  Vic|  f|2.0|   90.0|  55.5|    81.0| 32.0|    72.0|    49.4|13.4| 29.0| 31.0|
|  21|   1|  Vic|  f|3.0|   95.9|  58.1|    96.5| 39.5|    77.9|    52.9|14.2| 30.0| 40.0|
|  56|   4|other|  m|3.0|   99.9|  61.5|    93.7| 38.0|    68.7|    46.8|16.4| 27.5| 31.5|
|  31|   1|  Vic|  m|3.0|   92.8|  54.1|    93.0| 37.0|    68.0|    52.5|14.5| 27.0| 31.0|
|  85|   6|other|  m|3.0|   89.5|  56.2|    92.0| 40.5|    65.6|    43.5|14.5| 27.0| 31.5|
|  14|   1|  Vic|  m|3.0|   95.4|  57.6|    91.5| 36.0|    74.3|    53.7|15.1| 28.0| 31.5|
|  25|   1|  Vic|  m|3.0|   95.8|  58.5|    91.5| 35.5|    72.3|    51.6|14.9| 31.0| 35.0|
|  22|   1|  Vic|  m|3.0|   96.3|  58.5|    91.0| 39.5|    73.5|    52.1|16.2| 28.0| 36.0|
|  53|   3|other|  f|3.0|   93.1|  58.1|    91.0| 38.0|    67.4|    46.0|16.5| 26.0| 33.5|
|  58|   4|other|  m|3.0|   94.5|  64.2|    91.0| 39.0|    66.5|    46.4|14.4| 30.5| 33.0|
|  62|   5|other|  f|3.0|   91.3|  58.0|    90.5| 39.0|    65.5|    41.3|16.0| 27.0| 32.0|
|  64|   5|other|  f|3.0|   96.9|  56.5|    89.5| 38.5|    63.0|    45.1|17.1| 25.5| 33.0|
|  33|   1|  Vic|  m|3.0|   91.4|  54.6|    89.0| 37.0|    70.8|    51.8|14.8| 24.0| 30.0|
|  91|   7|other|  m|3.0|   97.8|  59.6|    89.0| 38.0|    65.5|    48.0|15.0| 26.0| 32.0|
| 104|   7|other|  f|3.0|   93.6|  59.9|    89.0| 40.0|    67.6|    46.0|14.8| 28.5| 33.5|
|  29|   1|  Vic|  f|3.0|   92.8|  56.0|    88.0| 35.0|    74.9|    51.8|14.0| 24.0| 32.0|
|  86|   6|other|  f|3.0|   88.2|  53.2|    86.5| 38.5|    60.3|    43.7|13.6| 26.0| 31.0|
|  99|   7|other|  f|3.0|   93.3|  56.2|    86.5| 38.5|    64.8|    43.8|14.0| 28.0| 35.0|
|  66|   5|other|  f|3.0|   90.4|  55.8|    86.0| 36.5|    63.2|    44.2|15.7| 26.5| 34.0|
|  97|   7|other|  m|3.0|   91.0|  53.1|    86.0| 38.0|    63.8|    46.0|14.5| 25.0| 31.5|
|  81|   6|other|  m|3.0|   90.6|  56.0|    85.5| 38.0|    65.6|    41.7|17.0| 27.5| 35.0|
|  90|   7|other|  m|3.0|   92.6|  54.6|    85.0| 38.5|    69.8|    44.8|14.5| 25.5| 32.5|
|  40|   2|  Vic|  f|3.0|   91.0|  55.0|    84.5| 36.0|    72.8|    51.4|13.6| 27.0| 30.0|
|  93|   7|other|  m|3.0|   89.2|  54.0|    82.0| 38.0|    63.8|    44.9|12.8| 24.0| 31.0|
|  83|   6|other|  f|3.0|   90.0|  53.8|    81.5| 36.0|    62.0|    43.3|14.0| 25.0| 29.0|
+----+----+-----+---+---+-------+------+--------+-----+--------+--------+----+-----+-----+
only showing top 50 rows

In [ ]:
spark.stop()